---
title: "ACR90"
subtitle: "Plan d'analyse"
thanks: "Ariane GILLET, Clélia DELETTRE - SAMU 95"
author: "Philippe MICHEL"
date: 08/09/2022
format: pdf
pdf-engine: lualatex
documentclass: scrartcl
mainfont: Adobe Garamond Pro
mainfontoptions:
- Ligatures = Common
- Ligatures = Rare
sansfont: Trajan Pro
monofont: Source Sans Pro
mathfont: Source Sans Pro
monofontoptions: Numbers = Monospaced
mathfontoptions: Numbers = Monospaced
colorlinks: true
fontsize: 10pt
papersize: a4
lang: fr
fig-align: center
toc: false
lof: false
lot: false
cite-method: biblatex
bibliography: stat.bib
license: MIT
always_allow_html: true
keep-tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
```

Ce document ne concerne que l'analyse statistique des données.

Il s'agit d'une étude purement observationnelle. Le risque $\alpha$ retenu est de 0,05 *&* la puissance de 0,8. Des graphiques seront réalisés pour tous les résultats intéressants. Le nombre de sujets nécessaire a été évalué à 74.

## Description de la population

La description de la population sera présentée sur un tableau avec toutes les données démographiques concernant le patient *&* l'appel (qui appelle, d'où etc.)

Les données numériques seront présentées par leur médiane avec les quartiles, les données catégorielles par le nombre *&* le pourcentage avec son intervalle de confiance calculé par bootstrap.

## Objectif principal

L'objectif principal est de détermier le temps entre le décroché *&* l'identification de l'ACR.  Ce temps sera calculé à partir des données enregistrées par le système de téléphonie du SAMU *&* présenté par sa médiane *&* les quartiles. 

Un lien entre les données concernant l'appel ou l'expérience de l'ARM *&* ce temps sera réalisé par des tests du $\chi^2$ pour les variables discrètes *&* des tests de Wilcoxon pour les données numériques. Une analyse multivariée par régression linéaire sera ensuite réalisée en incorporant dans un premier temps incorporant les toutes les variables ayant une p-value \< 0,20 sur l'analyse monovariée. Une recherche du meilleur modèle sera ensuite réalisé par un step-by-step descendant. Pour la détermination du meilleur modèle de régression logistique par step-by-step sur le critère principal, on utilisera un jeu de données après imputation des données manquantes. Par contre, une fois le modèle retenu, les calculs présentés seront réalisés sur les données réelles.

## Objectifs secondaires

### Données permettant l'identification de l'ACR ou rallongeant celle ci

 L'investigateur extraira des bandes les données concernées  *&* une liste sera constituée. La description sera présentée par le nombre *&* le pourcentage avec son intervalle de confiance calculé par bootstrap.
 
Une analyse en plein texte de l'entretien téléphonique centrée sur les déclarations de l’appelant sera réalisée sur un petit échantillon de 20 cas environ après lemmatisation par analyse factorielle *&* graphique (nuage de mots).

### Temps de recherche d'un DAE ou de proposition d'un MCE au témoin.

Ces temps seront calculés à partir des données enregistrées par le système de téléphonie du SAMU *&* présenté par sa médiane *&* les quartiles. 

### Ton de l'appel

Le ton de l'appel sera noté selon une échelle de Likert *à définir*. Une description sera présentée par le nombre *&* le pourcentage avec son intervalle de confiance calculé par bootstrap pour chaque classe.

## technique

L'analyse statistique sera réalisée grâce au logiciel `R` [@rstat] *&* à divers packages en particulier `tidyverse`[@tidy], `FactoMineR`[@facto] *&* `epiDisplay`[@epid].

